# Generated by Django 4.2.6 on 2024-01-13 07:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0002_chatmessage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Vector_db",
            new_name="Thread",
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="vector_db",
            new_name="thread",
        ),
    ]
