# Generated by Django 4.2.6 on 2024-01-23 11:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_collection_time_created_document_time_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thread",
            name="public",
        ),
    ]
