# Generated by Django 4.2.6 on 2024-01-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_remove_thread_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="loc",
            field=models.CharField(default=None, max_length=512),
            preserve_default=False,
        ),
    ]
