# Generated by Django 4.2.6 on 2024-01-28 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_collection_loc"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="base_collection",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.collection",
            ),
        ),
    ]
