# Generated by Django 4.2.6 on 2024-02-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_thread_base_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="sha256",
            field=models.CharField(default=None, max_length=64),
        ),
    ]
