# Generated by Django 4.2.6 on 2024-02-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_document_sha256"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="source_nodes",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
