# Generated by Django 4.2.6 on 2024-02-13 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_chatmessage_source_nodes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="source_nodes",
        ),
    ]
