# Generated by Django 4.2.9 on 2025-12-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_chatmessage_source_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_type',
            field=models.CharField(choices=[('document', 'Document-based Collection'), ('database', 'Database-backed Collection'), ('excel', 'Excel/CSV-backed Collection')], default='document', max_length=20),
        ),
        migrations.AddField(
            model_name='collection',
            name='db_connection_string',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='db_extra_knowledge',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='db_schema_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='db_type',
            field=models.CharField(blank=True, choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('sqlite', 'SQLite'), ('mongodb', 'MongoDB')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='excel_file_paths',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='docs',
            field=models.ManyToManyField(blank=True, related_name='collections', to='main.document'),
        ),
    ]
